language: node_js

sudo: false

before_script:
  - npm install -g bower
  - bower instasll -f

node_js:
  - '0.11'
  - '0.12'
  - 'iojs-v1.7.1'

matrix:
  allow_failures:
    - node_js: 'iojs-v1.7.1'

before_script:
  - phantomjs --version